version: '3.8'

services:
  webserver:
    build: .
    ports:
      - "8080:80"
    volumes:
      - web_data:/usr/share/nginx/html:ro
    container_name: nginx_volume_test

volumes:
  web_data:
    driver: local
